apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts/create
            pathType: ImplementationSpecific
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
          - path: /posts
            pathType: ImplementationSpecific
            backend:
              service:
                name: query-srv
                port:
                  number: 4002
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000

    # kubernetes.io/ingress.https-rules: '[{"host":"posts.com","path":"/posts/create","backend":{"serviceName":"posts-clusterip-srv","servicePort":"4000"}}]'
    # kubernetes.io/ingress.https-rules: '[{"host":"posts.com","path":"/posts","backend":{"serviceName":"query-srv","servicePort":"4002"}}]'
    # kubernetes.io/ingress.https-rules: '[{"host":"posts.com","path":"/posts/?(.*)/comments","backend":{"serviceName":"comments-srv","servicePort":"4001"}}]'
    # kubernetes.io/ingress.https-rules: '[{"host":"posts.com","path":"/?(.*)","backend":{"serviceName":"client-srv","servicePort":"3000"}}]'
    # kubernetes.io/ingress.rule-mix: "true"
